### ISSUE TITLE
我用的https的部署  solo老是自动重启个两三次然后就关机了

### ISSUE THREAD

**Issue by caldeer** [liumapp/solo-in-docker#10]
![image](https://user-images.githubusercontent.com/46398711/61870316-6330f080-af10-11e9-87bb-43567cc61128.png)
就是像这个样子然后就关了

**Comment by liumapp** [comment]
启动的命令换成 docker-compose up 

不要加-d参数，这样启动过程中的日志会直接打印在console上，你把出现的错误日志发这里

**Comment by caldeer** [comment]
![image](https://user-images.githubusercontent.com/46398711/61945846-8ffa0c00-afd3-11e9-9a15-5434f3647b98.png)

**Comment by caldeer** [comment]
![image](https://user-images.githubusercontent.com/46398711/61945881-aacc8080-afd3-11e9-823b-f7cbe52251c1.png)

**Comment by liumapp** [comment]
solo与数据库建立连接失败，把docker-compose的配置贴出来

**Comment by caldeer** [comment]
### docker-compose.yml
![image](https://user-images.githubusercontent.com/46398711/62000651-b375a180-b10e-11e9-9529-0d036aea1cd2.png)

**Comment by liumapp** [comment]
这个地方把mysql的密码换成初始默认密码 adminadmin试试
具体原因可以参考 https://github.com/liumapp/solo-in-docker/issues/7

**Comment by caldeer** [comment]
![image](https://user-images.githubusercontent.com/46398711/62015243-50524080-b1dc-11e9-992f-67552043cf1f.png)
大佬  WEB-INF/classes/latke.properties 这个目录在哪

**Comment by caldeer** [comment]
已解决
